# k8s/local/00-namespace.yaml
# Namespace pour l'application Quiz

apiVersion: v1
kind: Namespace
metadata:
  name: quiz-app
  labels:
    name: quiz-app
    environment: local
    managed-by: kubectl
